### ISSUE TITLE
Get rid of `std::future` in various JSON Schema related functions

### ISSUE THREAD

**Issue by jviotti** [sourcemeta/jsontoolkit#651]
Not really providing any value for the uses we have

**Comment by jviotti** [comment]
Related to this, seems like @michaelmior hit issues on older Ubuntu through https://github.com/sourcemeta/jsonschema

```
#0  0x00007ffff7dee221 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00007ffff7ddf6cb in std::__throw_system_error(int) () from /lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x000055555557d6d9 in std::call_once<void (std::__future_base::_State_baseV2::*)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*>(std::once_flag&, void (std::__future_base::_State_baseV2::*&&)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*&&, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*&&, bool*&&) (
    __once=..., __f=
    @0x7fffffff4968: (void (std::__future_base::_State_baseV2::*)(std::__future_base::_State_baseV2 * const, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()> *, bool *)) 0x55555557d6e0 <std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)>, __args=@0x7fffffff4950: 0x7fffffff497e,
    __args=@0x7fffffff4950: 0x7fffffff497e, __args=@0x7fffffff4950: 0x7fffffff497e) at /usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/mutex:737
#3  0x000055555557d475 in std::__future_base::_State_baseV2::_M_set_result(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>, bool) (this=0x555555909220, __res=...,
    __ignore_failure=false) at /usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/future:412
#4  0x00005555555df82e in std::promise<std::optional<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::set_value (this=0x7fffffff4d10, __r=...)
    at /usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/future:1125
#5  0x00005555555da8b9 in sourcemeta::jsontoolkit::base_dialect(sourcemeta::jsontoolkit::JSON const&, std::function<std::future<std::optional<sourcemeta::jsontoolkit::JSON> > (std::basic_string_view<char, std::char_traits<char> >)> const&, std::optional<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const&) (schema=..., resolver=..., default_dialect=std::optional<std::string> [no contained value])
    at /tmp/jsonschema/vendor/jsontoolkit/src/jsonschema/jsonschema.cc:268
#6  0x00005555555dcb18 in sourcemeta::jsontoolkit::vocabularies(sourcemeta::jsontoolkit::JSON const&, std::function<std::future<std::optional<sourcemeta::jsontoolkit::JSON> > (std::basic_string_view<char, std::char_traits<char> >)> const&, std::optional<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const&) (schema=..., resolver=..., default_dialect=std::optional<std::string> [no contained value])
    at /tmp/jsonschema/vendor/jsontoolkit/src/jsonschema/jsonschema.cc:317
#7  0x000055555561cdc0 in sourcemeta::jsontoolkit::bundle(sourcemeta::jsontoolkit::JSON&, std::function<sourcemeta::jsontoolkit::SchemaWalkerResult (std::basic_string_view<char, std::char_traits<char> >, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, bool> > > const&)> const&, std::function<std::future<std::optional<sourcemeta::jsontoolkit::JSON> > (std::basic_string_view<char, std::char_traits<char> >)> const&, sourcemeta::jsontoolkit::BundleOptions, std::optional<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const&) (schema=..., walker=..., resolver=..., options=sourcemeta::jsontoolkit::BundleOptions::Default,
    default_dialect=std::optional<std::string> [no contained value]) at /tmp/jsonschema/vendor/jsontoolkit/src/jsonschema/bundle.cc:203
#8  0x000055555561f008 in sourcemeta::jsontoolkit::bundle(sourcemeta::jsontoolkit::JSON const&, std::function<sourcemeta::jsontoolkit::SchemaWalkerResult (std::basic_string_view<char, std::char_traits<char> >, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, bool> > > const&)> const&, std::function<std::future<std::optional<sourcemeta::jsontoolkit::JSON> > (std::basic_string_view<char, std::char_traits<char> >)> const&, sourcemeta::jsontoolkit::BundleOptions, std::optional<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const&) (schema=..., walker=..., resolver=..., options=sourcemeta::jsontoolkit::BundleOptions::Default,
    default_dialect=std::optional<std::string> [no contained value]) at /tmp/jsonschema/vendor/jsontoolkit/src/jsonschema/bundle.cc:222
#9  0x000055555562050b in _ZN10sourcemeta11jsontoolkit7compileERKNS0_4JSONERKSt8functionIFNS0_18SchemaWalkerResultESt17basic_string_viewIcSt11char_traitsIcEERKSt3mapINSt7__cxx1112basic_stringIcS8_SaIcEEEbSt4lessISE_ESaISt4pairIKSE_bEEEEERKS4_IFSt6futureISt8optionalIS1_EES9_EERKS4_IFSt6vectorISt7variantIJNS0_27SchemaCompilerAssertionFailENS0_30SchemaCompilerAssertionDefinesENS0_33SchemaCompilerAssertionDefinesAllENS0_27SchemaCompilerAssertionTypeENS0_30SchemaCompilerAssertionTypeAnyENS0_33SchemaCompilerAssertionTypeStrictENS0_36SchemaCompilerAssertionTypeStrictAnyENS0_28SchemaCompilerAssertionRegexENS0_34SchemaCompilerAssertionSizeGreaterENS0_31SchemaCompilerAssertionSizeLessENS0_28SchemaCompilerAssertionEqualENS0_32SchemaCompilerAssertionEqualsAnyENS0_35SchemaCompilerAssertionGreaterEqualENS0_32SchemaCompilerAssertionLessEqualENS0_30SchemaCompilerAssertionGreaterENS0_27SchemaCompilerAssertionLessENS0_29SchemaCompilerAssertionUniqueENS0_32SchemaCompilerAssertionDivisibleENS0_33SchemaCompilerAssertionStringTypeENS0_32SchemaCompilerAssertionSizeEqualENS0_33SchemaCompilerAssertionAnnotationENS0_43SchemaCompilerAssertionNoAdjacentAnnotationENS0_35SchemaCompilerAssertionNoAnnotationENS0_28SchemaCompilerAnnotationEmitENS0_23SchemaCompilerLogicalOrENS0_24SchemaCompilerLogicalAndENS0_24SchemaCompilerLogicalXorENS0_24SchemaCompilerLogicalTryENS0_24SchemaCompilerLogicalNotENS0_28SchemaCompilerLoopPropertiesENS0_22SchemaCompilerLoopKeysENS0_23SchemaCompilerLoopItemsENS0_42SchemaCompilerLoopItemsFromAnnotationIndexENS0_26SchemaCompilerLoopContainsENS0_26SchemaCompilerControlLabelENS0_25SchemaCompilerControlMarkENS0_25SchemaCompilerControlJumpENS0_38SchemaCompilerControlDynamicAnchorJumpEEESaIS24_EERKNS0_21SchemaCompilerContextERKNS0_27SchemaCompilerSchemaContextERKNS0_28SchemaCompilerDynamicContextEEENS0_29SchemaCompilerCompilationModeERKST_ISE_E (schema=..., walker=...,
    resolver=..., compiler=..., mode=sourcemeta::jsontoolkit::SchemaCompilerCompilationMode::Optimized, default_dialect=std::optional<std::string> [no contained value]) at /tmp/jsonschema/vendor/jsontoolkit/src/jsonschema/compile.cc:75
#10 0x00005555555b692b in sourcemeta::jsonschema::cli::validate (arguments=std::span of length 3 = {...}) at /tmp/jsonschema/src/command_validate.cc:51
#11 0x0000555555565b09 in jsonschema_main (program="/home/mmior/bin/iai-jsonschema", command="validate", arguments=std::span of length 3 = {...}) at /tmp/jsonschema/src/main.cc:88
#12 0x0000555555565ead in main (argc=5, argv=0x7fffffff7948) at /tmp/jsonschema/src/main.cc:111
```

**Comment by jviotti** [comment]
@tony-go This is an easy one in case you want to also get exposure to other parts of the codebase, plus it might fix things for @michaelmior :D

**Comment by jviotti** [comment]
Re-opening as there are a few more cases
